import type { DirectoryParticipant } from "@/components/participant-directory/types";

export const demoParticipants: DirectoryParticipant[] = [
  {
    id: "demo-laura",
    degree: "Ingeniería Informática",
    company: "Nébula Labs",
    team: { id: "demo-orbita", name: "Órbita" },
    university: "Universidad Politécnica de Madrid",
    interests: ["Agentes IA", "Educación", "Open source"],
    displayName: "Laura Martín",
    role: "AI Engineer",
    city: "Madrid",
    skills: ["Python", "LLM", "Agents"],
    featured: true,
    bio: "Construye agentes que pasan del notebook a producción.",
    lore: "Convierte una demo de madrugada en producto antes del desayuno.",
  },
  {
    id: "demo-alex",
    degree: "Ingeniería Informática",
    company: "Estudio Prisma",
    team: { id: "demo-prisma", name: "Prisma" },
    university: "Universitat Politècnica de València",
    interests: ["Open source", "Herramientas dev"],
    displayName: "Álex Romero",
    role: "Frontend Developer",
    city: "Valencia",
    skills: ["React", "TypeScript", "CSS"],
    bio: "Transforma ideas en interfaces rápidas y accesibles.",
    lore: "Siempre encuentra tiempo para pulir el último detalle.",
  },
  {
    id: "demo-nora",
    degree: "Diseño",
    company: "Estudio Prisma",
    team: { id: "demo-prisma", name: "Prisma" },
    university: "Universitat de Barcelona",
    interests: ["Educación", "Diseño accesible"],
    displayName: "Nora Vidal",
    role: "Product Designer",
    city: "Barcelona",
    skills: ["Figma", "UX", "Prototipado"],
    bio: "Diseña productos que se entienden desde el primer clic.",
    lore: "Llega con preguntas y sale con un prototipo.",
  },
  {
    id: "demo-diego",
    degree: "Ingeniería Informática",
    company: "Atlas Cloud",
    team: { id: "demo-nexo", name: "Nexo" },
    university: "Universidad de Sevilla",
    interests: ["Herramientas dev", "Open source"],
    displayName: "Diego Castro",
    role: "Backend Developer",
    city: "Sevilla",
    skills: ["Go", "PostgreSQL", "Docker"],
    bio: "Construye APIs y sistemas que aguantan el ritmo del equipo.",
    lore: "Su demo también funciona cuando falla el wifi.",
  },
  {
    id: "demo-elena",
    degree: "Ciencia de Datos",
    company: "Raíz Data",
    team: { id: "demo-raiz", name: "Raíz" },
    university: "Universidad del País Vasco",
    interests: ["Agentes IA", "Sostenibilidad"],
    displayName: "Elena Ríos",
    role: "Data Scientist",
    city: "Bilbao",
    skills: ["Python", "SQL", "Machine Learning"],
    bio: "Convierte datos difíciles en decisiones claras.",
    lore: "Encuentra el patrón que nadie había visto.",
  },
  {
    id: "demo-marcos",
    degree: "Ingeniería Informática",
    company: "Nébula Labs",
    team: { id: "demo-orbita", name: "Órbita" },
    university: "Universidad Politécnica de Madrid",
    interests: ["Open source", "Educación"],
    displayName: "Marcos Vega",
    role: "Full Stack Developer",
    city: "Madrid",
    skills: ["Next.js", "TypeScript", "Convex"],
    bio: "Conecta diseño, frontend y backend para poner productos en marcha.",
    lore: "Del primer commit a la demo en un fin de semana.",
  },
  {
    id: "demo-sara",
    degree: "Matemáticas",
    company: "Nébula Labs",
    team: { id: "demo-orbita", name: "Órbita" },
    displayName: "Sara Alonso",
    city: "Madrid",
    university: "Universidad Complutense de Madrid",
    role: "ML Engineer",
    skills: ["Python", "PyTorch", "LLM"],
    interests: ["Agentes IA", "Salud"],
    bio: "Explora modelos pequeños para resolver problemas grandes.",
  },
  {
    id: "demo-pablo",
    degree: "Ingeniería Informática",
    company: "Atlas Cloud",
    team: { id: "demo-nexo", name: "Nexo" },
    displayName: "Pablo Torres",
    city: "Madrid",
    university: "Universidad Politécnica de Madrid",
    role: "Backend Developer",
    skills: ["Go", "Docker", "Python"],
    interests: ["Open source", "Herramientas dev"],
    bio: "Quiere construir infraestructura sencilla que cualquiera pueda usar.",
  },
  {
    id: "demo-ines",
    degree: "Matemáticas",
    company: "Nébula Labs",
    displayName: "Inés Costa",
    city: "Barcelona",
    university: "Universitat Politècnica de Catalunya",
    role: "AI Researcher",
    skills: ["Python", "LLM", "Agents"],
    interests: ["Agentes IA", "Educación"],
    bio: "Investiga cómo hacer que los agentes colaboren con las personas.",
  },
  {
    id: "demo-hugo",
    degree: "Ingeniería Informática",
    company: "Estudio Prisma",
    team: { id: "demo-prisma", name: "Prisma" },
    displayName: "Hugo Santos",
    city: "Valencia",
    university: "Universitat Politècnica de València",
    role: "Product Engineer",
    skills: ["React", "TypeScript", "Next.js"],
    interests: ["Educación", "Herramientas dev"],
    bio: "Le interesa convertir ideas educativas en productos útiles.",
  },
  {
    id: "demo-lucia",
    degree: "Diseño",
    company: "Estudio Prisma",
    displayName: "Lucía Navarro",
    city: "Madrid",
    university: "Universidad Carlos III de Madrid",
    role: "Product Designer",
    skills: ["Figma", "UX", "Prototipado"],
    interests: ["Educación", "Diseño accesible"],
    bio: "Diseña experiencias que acercan la tecnología a más personas.",
  },
  {
    id: "demo-omar",
    degree: "Ciencia de Datos",
    company: "Raíz Data",
    team: { id: "demo-raiz", name: "Raíz" },
    displayName: "Omar Benali",
    city: "Sevilla",
    university: "Universidad de Sevilla",
    role: "Data Engineer",
    skills: ["Python", "SQL", "Docker"],
    interests: ["Sostenibilidad", "Open source"],
    bio: "Le gusta conectar datos abiertos y proyectos con impacto local.",
  },
  {
    id: "demo-clara",
    degree: "Diseño",
    displayName: "Clara Soler",
    city: "Barcelona",
    university: "Universitat de Barcelona",
    role: "Frontend Developer",
    skills: ["React", "CSS", "Figma"],
    interests: ["Diseño accesible", "Open source"],
    bio: "Busca un equipo que cuide tanto la accesibilidad como el código.",
  },
  {
    id: "demo-bruno",
    degree: "Ingeniería Informática",
    company: "Atlas Cloud",
    team: { id: "demo-nexo", name: "Nexo" },
    displayName: "Bruno Gil",
    city: "Bilbao",
    university: "Universidad del País Vasco",
    role: "Full Stack Developer",
    skills: ["TypeScript", "Convex", "SQL"],
    interests: ["Herramientas dev", "Sostenibilidad"],
    bio: "Construye herramientas para simplificar el trabajo en equipo.",
  },
  {
    id: "demo-eva",
    degree: "Ingeniería Electrónica",
    displayName: "Eva Prieto",
    city: "Madrid",
    university: "Universidad Politécnica de Madrid",
    role: "Robotics Engineer",
    skills: ["Python", "C++", "ROS"],
    interests: ["Robótica", "Sostenibilidad"],
    bio: "Mezcla hardware y software para llevar las ideas al mundo físico.",
  },
  {
    id: "demo-leo",
    degree: "Matemáticas",
    displayName: "Leo Ferrer",
    city: "Valencia",
    university: "Universitat Politècnica de València",
    role: "AI Engineer",
    skills: ["Python", "Agents", "LLM"],
    interests: ["Agentes IA", "Open source"],
    bio: "Crea agentes y comparte lo que aprende por el camino.",
  },
  {
    id: "demo-ana",
    degree: "Ciencia de Datos",
    company: "Raíz Data",
    team: { id: "demo-raiz", name: "Raíz" },
    displayName: "Ana León",
    city: "Madrid",
    university: "Universidad Complutense de Madrid",
    role: "Data Scientist",
    skills: ["Python", "SQL", "Machine Learning"],
    interests: ["Educación", "Salud"],
    bio: "Quiere que los datos ayuden a tomar decisiones más claras.",
  },
  {
    id: "demo-mateo",
    degree: "Bellas Artes",
    displayName: "Mateo Ruiz",
    city: "Zaragoza",
    university: "Universidad de Zaragoza",
    role: "Game Developer",
    skills: ["Unity", "C#", "Blender"],
    interests: ["Videojuegos", "Arte digital"],
    bio: "Busca colaboradores para crear experiencias de juego experimentales.",
  },
];
