import type { DirectoryParticipant } from "@/components/participant-directory/types";

export const demoParticipants: DirectoryParticipant[] = [
  {
    bio: "Construye agentes que pasan del notebook a producción.",
    city: "Madrid",
    company: "Nébula Labs",
    degree: "Ingeniería Informática",
    displayName: "Laura Martín",
    featured: true,
    id: "demo-laura",
    interests: ["Agentes IA", "Educación", "Open source"],
    lore: "Convierte una demo de madrugada en producto antes del desayuno.",
    role: "AI Engineer",
    skills: ["Python", "LLM", "Agents"],
    team: { id: "demo-orbita", name: "Órbita" },
    university: "Universidad Politécnica de Madrid",
  },
  {
    bio: "Transforma ideas en interfaces rápidas y accesibles.",
    city: "Valencia",
    company: "Estudio Prisma",
    degree: "Ingeniería Informática",
    displayName: "Álex Romero",
    id: "demo-alex",
    interests: ["Open source", "Herramientas dev"],
    lore: "Siempre encuentra tiempo para pulir el último detalle.",
    role: "Frontend Developer",
    skills: ["React", "TypeScript", "CSS"],
    team: { id: "demo-prisma", name: "Prisma" },
    university: "Universitat Politècnica de València",
  },
  {
    bio: "Diseña productos que se entienden desde el primer clic.",
    city: "Barcelona",
    company: "Estudio Prisma",
    degree: "Diseño",
    displayName: "Nora Vidal",
    id: "demo-nora",
    interests: ["Educación", "Diseño accesible"],
    lore: "Llega con preguntas y sale con un prototipo.",
    role: "Product Designer",
    skills: ["Figma", "UX", "Prototipado"],
    team: { id: "demo-prisma", name: "Prisma" },
    university: "Universitat de Barcelona",
  },
  {
    bio: "Construye APIs y sistemas que aguantan el ritmo del equipo.",
    city: "Sevilla",
    company: "Atlas Cloud",
    degree: "Ingeniería Informática",
    displayName: "Diego Castro",
    id: "demo-diego",
    interests: ["Herramientas dev", "Open source"],
    lore: "Su demo también funciona cuando falla el wifi.",
    role: "Backend Developer",
    skills: ["Go", "PostgreSQL", "Docker"],
    team: { id: "demo-nexo", name: "Nexo" },
    university: "Universidad de Sevilla",
  },
  {
    bio: "Convierte datos difíciles en decisiones claras.",
    city: "Bilbao",
    company: "Raíz Data",
    degree: "Ciencia de Datos",
    displayName: "Elena Ríos",
    id: "demo-elena",
    interests: ["Agentes IA", "Sostenibilidad"],
    lore: "Encuentra el patrón que nadie había visto.",
    role: "Data Scientist",
    skills: ["Python", "SQL", "Machine Learning"],
    team: { id: "demo-raiz", name: "Raíz" },
    university: "Universidad del País Vasco",
  },
  {
    bio: "Conecta diseño, frontend y backend para poner productos en marcha.",
    city: "Madrid",
    company: "Nébula Labs",
    degree: "Ingeniería Informática",
    displayName: "Marcos Vega",
    id: "demo-marcos",
    interests: ["Open source", "Educación"],
    lore: "Del primer commit a la demo en un fin de semana.",
    role: "Full Stack Developer",
    skills: ["Next.js", "TypeScript", "Convex"],
    team: { id: "demo-orbita", name: "Órbita" },
    university: "Universidad Politécnica de Madrid",
  },
  {
    bio: "Explora modelos pequeños para resolver problemas grandes.",
    city: "Madrid",
    company: "Nébula Labs",
    degree: "Matemáticas",
    displayName: "Sara Alonso",
    id: "demo-sara",
    interests: ["Agentes IA", "Salud"],
    role: "ML Engineer",
    skills: ["Python", "PyTorch", "LLM"],
    team: { id: "demo-orbita", name: "Órbita" },
    university: "Universidad Complutense de Madrid",
  },
  {
    bio: "Quiere construir infraestructura sencilla que cualquiera pueda usar.",
    city: "Madrid",
    company: "Atlas Cloud",
    degree: "Ingeniería Informática",
    displayName: "Pablo Torres",
    id: "demo-pablo",
    interests: ["Open source", "Herramientas dev"],
    role: "Backend Developer",
    skills: ["Go", "Docker", "Python"],
    team: { id: "demo-nexo", name: "Nexo" },
    university: "Universidad Politécnica de Madrid",
  },
  {
    bio: "Investiga cómo hacer que los agentes colaboren con las personas.",
    city: "Barcelona",
    company: "Nébula Labs",
    degree: "Matemáticas",
    displayName: "Inés Costa",
    id: "demo-ines",
    interests: ["Agentes IA", "Educación"],
    role: "AI Researcher",
    skills: ["Python", "LLM", "Agents"],
    university: "Universitat Politècnica de Catalunya",
  },
  {
    bio: "Le interesa convertir ideas educativas en productos útiles.",
    city: "Valencia",
    company: "Estudio Prisma",
    degree: "Ingeniería Informática",
    displayName: "Hugo Santos",
    id: "demo-hugo",
    interests: ["Educación", "Herramientas dev"],
    role: "Product Engineer",
    skills: ["React", "TypeScript", "Next.js"],
    team: { id: "demo-prisma", name: "Prisma" },
    university: "Universitat Politècnica de València",
  },
  {
    bio: "Diseña experiencias que acercan la tecnología a más personas.",
    city: "Madrid",
    company: "Estudio Prisma",
    degree: "Diseño",
    displayName: "Lucía Navarro",
    id: "demo-lucia",
    interests: ["Educación", "Diseño accesible"],
    role: "Product Designer",
    skills: ["Figma", "UX", "Prototipado"],
    university: "Universidad Carlos III de Madrid",
  },
  {
    bio: "Le gusta conectar datos abiertos y proyectos con impacto local.",
    city: "Sevilla",
    company: "Raíz Data",
    degree: "Ciencia de Datos",
    displayName: "Omar Benali",
    id: "demo-omar",
    interests: ["Sostenibilidad", "Open source"],
    role: "Data Engineer",
    skills: ["Python", "SQL", "Docker"],
    team: { id: "demo-raiz", name: "Raíz" },
    university: "Universidad de Sevilla",
  },
  {
    bio: "Busca un equipo que cuide tanto la accesibilidad como el código.",
    city: "Barcelona",
    degree: "Diseño",
    displayName: "Clara Soler",
    id: "demo-clara",
    interests: ["Diseño accesible", "Open source"],
    role: "Frontend Developer",
    skills: ["React", "CSS", "Figma"],
    university: "Universitat de Barcelona",
  },
  {
    bio: "Construye herramientas para simplificar el trabajo en equipo.",
    city: "Bilbao",
    company: "Atlas Cloud",
    degree: "Ingeniería Informática",
    displayName: "Bruno Gil",
    id: "demo-bruno",
    interests: ["Herramientas dev", "Sostenibilidad"],
    role: "Full Stack Developer",
    skills: ["TypeScript", "Convex", "SQL"],
    team: { id: "demo-nexo", name: "Nexo" },
    university: "Universidad del País Vasco",
  },
  {
    bio: "Mezcla hardware y software para llevar las ideas al mundo físico.",
    city: "Madrid",
    degree: "Ingeniería Electrónica",
    displayName: "Eva Prieto",
    id: "demo-eva",
    interests: ["Robótica", "Sostenibilidad"],
    role: "Robotics Engineer",
    skills: ["Python", "C++", "ROS"],
    university: "Universidad Politécnica de Madrid",
  },
  {
    bio: "Crea agentes y comparte lo que aprende por el camino.",
    city: "Valencia",
    degree: "Matemáticas",
    displayName: "Leo Ferrer",
    id: "demo-leo",
    interests: ["Agentes IA", "Open source"],
    role: "AI Engineer",
    skills: ["Python", "Agents", "LLM"],
    university: "Universitat Politècnica de València",
  },
  {
    bio: "Quiere que los datos ayuden a tomar decisiones más claras.",
    city: "Madrid",
    company: "Raíz Data",
    degree: "Ciencia de Datos",
    displayName: "Ana León",
    id: "demo-ana",
    interests: ["Educación", "Salud"],
    role: "Data Scientist",
    skills: ["Python", "SQL", "Machine Learning"],
    team: { id: "demo-raiz", name: "Raíz" },
    university: "Universidad Complutense de Madrid",
  },
  {
    bio: "Busca colaboradores para crear experiencias de juego experimentales.",
    city: "Zaragoza",
    degree: "Bellas Artes",
    displayName: "Mateo Ruiz",
    id: "demo-mateo",
    interests: ["Videojuegos", "Arte digital"],
    role: "Game Developer",
    skills: ["Unity", "C#", "Blender"],
    university: "Universidad de Zaragoza",
  },
];
