import codeRaw from "../../assets/illustration-code.svg?raw";
import communityRaw from "../../assets/illustration-community.svg?raw";
import compassRaw from "../../assets/illustration-compass.svg?raw";
import horseRaw from "../../assets/illustration-horse.svg?raw";
import medalRaw from "../../assets/illustration-medal.svg?raw";
import quixoteRaw from "../../assets/illustration-quixote.svg?raw";
import sparkRaw from "../../assets/illustration-spark.svg?raw";
import sunRaw from "../../assets/illustration-sun.svg?raw";
import trophyRaw from "../../assets/illustration-trophy.svg?raw";
import windmillRaw from "../../assets/illustration-windmill.svg?raw";
import logoRaw from "../../assets/logo.svg?raw";
import acurioSvg from "../../assets/sponsors/acurio.svg";
import causaPrimaSvg from "../../assets/sponsors/causa_prima.svg";
import cloudflareSvg from "../../assets/sponsors/cloudflare.svg";
import cognitionSvg from "../../assets/sponsors/cognition.svg";
import convexSvg from "../../assets/sponsors/convex.svg";
import cursorSvg from "../../assets/sponsors/cursor.svg";
import embatPng from "../../assets/sponsors/embat.png";
import enzoSvg from "../../assets/sponsors/enzo.svg";
import exaSvg from "../../assets/sponsors/exa.svg";
import exponentialPng from "../../assets/sponsors/exponential.png";
import falSvg from "../../assets/sponsors/fal.svg";
import happyrobotPng from "../../assets/sponsors/happyrobot.png";
import helmcodeSvg from "../../assets/sponsors/helmcode.svg";
import invopopSvg from "../../assets/sponsors/invopop.svg";
import jmeSvg from "../../assets/sponsors/jme.svg";
import karumiSvg from "../../assets/sponsors/karumi.svg";
import kfundPng from "../../assets/sponsors/kfund.png";
import kiboSvg from "../../assets/sponsors/kibo.svg";
import maisaPng from "../../assets/sponsors/maisa.png";
import onecoworkSvg from "../../assets/sponsors/onecowork.svg";
import prosperAiSvg from "../../assets/sponsors/prosper_ai.svg";
import quiverAiSvg from "../../assets/sponsors/quiver_ai.svg";
import reveniSvg from "../../assets/sponsors/reveni.svg";
import revenuecatSvg from "../../assets/sponsors/revenuecat.svg";
import thekerSvg from "../../assets/sponsors/theker.svg";
import tinybirdSvg from "../../assets/sponsors/tinybird.svg";
import upmPng from "../../assets/sponsors/upm.png";
import vercelSvg from "../../assets/sponsors/vercel.svg";
import { prepareIllustrationSvg } from "../svg/prepare-illustration-svg";
import { prepareLogoSvg } from "../svg/prepare-logo-svg";

export const windmillSvg = prepareIllustrationSvg(windmillRaw);
export const horseSvg = prepareIllustrationSvg(horseRaw);
export const sunSvg = prepareIllustrationSvg(sunRaw);
export const quixoteSvg = prepareIllustrationSvg(quixoteRaw);
export const sparkSvg = prepareIllustrationSvg(sparkRaw);
export const codeSvg = prepareIllustrationSvg(codeRaw);
export const communitySvg = prepareIllustrationSvg(communityRaw);
export const trophySvg = prepareIllustrationSvg(trophyRaw);
export const compassSvg = prepareIllustrationSvg(compassRaw);
export const medalSvg = prepareIllustrationSvg(medalRaw);
export const logoSvg = prepareLogoSvg(logoRaw);
export const happyrobotLogo = happyrobotPng;
export const maisaLogo = maisaPng;

export const cloudflareLogo = cloudflareSvg;
export const convexLogo = convexSvg;
export const exaLogo = exaSvg;
export const falLogo = falSvg;
export const cognitionLogo = cognitionSvg;
export const cursorLogo = cursorSvg;
export const helmcodeLogo = helmcodeSvg;
export const quiverAiLogo = quiverAiSvg;
export const tinybirdLogo = tinybirdSvg;
export const vercelLogo = vercelSvg;

/** Grand prize backers — see data/grand-prize-sponsors.ts. */
export const kfundLogo = kfundPng;
export const jmeLogo = jmeSvg;
export const kiboLogo = kiboSvg;
export const enzoLogo = enzoSvg;
export const acurioLogo = acurioSvg;
export const embatLogo = embatPng;
export const exponentialLogo = exponentialPng;
export const upmLogo = upmPng;
export const onecoworkLogo = onecoworkSvg;
export const prosperAiLogo = prosperAiSvg;
export const theckerLogo = thekerSvg;

/** Comida, bebida y charlas — see MENTOR_SPONSORS in sections/partner-logos. */
export const revenuecatLogo = revenuecatSvg;
export const reveniLogo = reveniSvg;
export const karumiLogo = karumiSvg;
export const invopopLogo = invopopSvg;
export const causaPrimaLogo = causaPrimaSvg;
